// Code generated by mockery v2.32.4. DO NOT EDIT.

package storage

import mock "github.com/stretchr/testify/mock"

// MockArtifactStorageFactoryProvider is an autogenerated mock type for the ArtifactStorageFactoryProvider type
type MockArtifactStorageFactoryProvider struct {
	mock.Mock
}

// GetStorage provides a mock function with given fields: runArtifactPath
func (_m *MockArtifactStorageFactoryProvider) GetStorage(runArtifactPath string) (ArtifactStorageProvider, error) {
	ret := _m.Called(runArtifactPath)

	var r0 ArtifactStorageProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ArtifactStorageProvider, error)); ok {
		return rf(runArtifactPath)
	}
	if rf, ok := ret.Get(0).(func(string) ArtifactStorageProvider); ok {
		r0 = rf(runArtifactPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ArtifactStorageProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runArtifactPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockArtifactStorageFactoryProvider creates a new instance of MockArtifactStorageFactoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtifactStorageFactoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtifactStorageFactoryProvider {
	mock := &MockArtifactStorageFactoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
