// Code generated by mockery v2.34.0. DO NOT EDIT.

package repositories

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockBaseRepositoryProvider is an autogenerated mock type for the BaseRepositoryProvider type
type MockBaseRepositoryProvider struct {
	mock.Mock
}

// GetDB provides a mock function with given fields:
func (_m *MockBaseRepositoryProvider) GetDB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockBaseRepositoryProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockBaseRepositoryProvider creates a new instance of MockBaseRepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBaseRepositoryProvider(t mockConstructorTestingTNewMockBaseRepositoryProvider) *MockBaseRepositoryProvider {
	mock := &MockBaseRepositoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
